import pygame
from constants import *
from icons import *
from sounds import *

#Controlar el Volumen
def control_volume(screen, volume):
    if (volume):
        screen.blit(full_volume, (volume_x, volume_y), full_volume.get_rect())
        pygame.mixer.music.set_volume(0.2)
        thunder.set_volume(0.2)
        scream_logo_sound.set_volume(0.7)
        whispers_start.set_volume(0.7)
        bullying.set_volume(0.3)
        interference.set_volume(0.4)
        scream_echo.set_volume(0.7)
        hit_crate.set_volume(0.6)
        broken_crate.set_volume(0.6)
        lock.set_volume(0.9)
        unlock.set_volume(0.9)
        open_door.set_volume(0.9)
        scream_monster_one.set_volume(0.9)
        evil_laugh.set_volume(0.7)
        broken_bulb.set_volume(0.8)
        wrong_code.set_volume(0.7)
        correct_code.set_volume(0.7)
        scream_monster_two.set_volume(0.9)
        timer.set_volume(0.2)
        bad_ending_bell.set_volume(0.9)
        whispers.set_volume(0.8)
        scream_monster_three.set_volume(1)
        screams.set_volume(1)
        correct.set_volume(1)
        final_good_ending.set_volume(0.7)
    else:
        screen.blit(void_volume, (volume_x, volume_y), void_volume.get_rect())
        pygame.mixer.music.set_volume(0)
        thunder.set_volume(0)
        scream_logo_sound.set_volume(0)
        whispers_start.set_volume(0)
        bullying.set_volume(0)
        interference.set_volume(0)
        scream_echo.set_volume(0)
        hit_crate.set_volume(0)
        broken_crate.set_volume(0)
        lock.set_volume(0)
        unlock.set_volume(0)
        open_door.set_volume(0)
        scream_monster_one.set_volume(0)
        evil_laugh.set_volume(0)
        broken_bulb.set_volume(0)
        wrong_code.set_volume(0)
        correct_code.set_volume(0)
        scream_monster_two.set_volume(0)
        timer.set_volume(0)
        bad_ending_bell.set_volume(0)
        whispers.set_volume(0)
        scream_monster_three.set_volume(0)
        screams.set_volume(0)
        correct.set_volume(0)
        final_good_ending.set_volume(0)